// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPrzARIVdp0UmYycFI5Chx8MgNgUa3u6I',
    appId: '1:975830813530:web:cd65be40a2437ca235c163',
    messagingSenderId: '975830813530',
    projectId: 'liflow-c4a7d',
    authDomain: 'liflow-c4a7d.firebaseapp.com',
    storageBucket: 'liflow-c4a7d.firebasestorage.app',
    measurementId: 'G-N213SD8EPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFw1Gt5OsqeyDZfCvI6M91ArK1SNtV_EI',
    appId: '1:975830813530:android:223fa975a666642035c163',
    messagingSenderId: '975830813530',
    projectId: 'liflow-c4a7d',
    storageBucket: 'liflow-c4a7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfvCzdYYOmqvs3xSs-A164QmyOBmKjvHw',
    appId: '1:975830813530:ios:74056779321f2de635c163',
    messagingSenderId: '975830813530',
    projectId: 'liflow-c4a7d',
    storageBucket: 'liflow-c4a7d.firebasestorage.app',
    iosBundleId: 'com.example.liflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfvCzdYYOmqvs3xSs-A164QmyOBmKjvHw',
    appId: '1:975830813530:ios:74056779321f2de635c163',
    messagingSenderId: '975830813530',
    projectId: 'liflow-c4a7d',
    storageBucket: 'liflow-c4a7d.firebasestorage.app',
    iosBundleId: 'com.example.liflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPrzARIVdp0UmYycFI5Chx8MgNgUa3u6I',
    appId: '1:975830813530:web:53f1d0a3e4f6342e35c163',
    messagingSenderId: '975830813530',
    projectId: 'liflow-c4a7d',
    authDomain: 'liflow-c4a7d.firebaseapp.com',
    storageBucket: 'liflow-c4a7d.firebasestorage.app',
    measurementId: 'G-G14PK092LM',
  );
}
